namespace CUE4Parse.UE4.Assets.Exports.Material;

public enum EShaderPlatform : byte
{
	SP_PCD3D_SM5 = 0,
	SP_METAL = 11,
	SP_METAL_MRT = 12,
	SP_PCD3D_ES3_1 = 14,
	SP_OPENGL_PCES3_1 = 15,
	SP_METAL_SM5 = 16,
	SP_VULKAN_PCES3_1 = 17,
	SP_METAL_SM5_NOTESS_REMOVED = 18,
	SP_VULKAN_SM5 = 20,
	SP_VULKAN_ES3_1_ANDROID = 21,
	SP_METAL_MACES3_1 = 22,
	SP_OPENGL_ES3_1_ANDROID = 24,
	SP_METAL_MRT_MAC = 27,
	SP_VULKAN_SM5_LUMIN_REMOVED = 28,
	SP_VULKAN_ES3_1_LUMIN_REMOVED = 29,
	SP_METAL_TVOS = 30,
	SP_METAL_MRT_TVOS = 31,
	SP_StaticPlatform_First = 32,
	DDPI_EXTRA_SHADERPLATFORMS = 33,
	SP_StaticPlatform_Last = 47,
	SP_VULKAN_SM5_ANDROID = 48,
	SP_PCD3D_SM6 = 49,
	SP_NumPlatforms = 50,
	SP_NumBits = 7
}
