namespace CUE4Parse.UE4.Assets.Exports.Material;

public enum EUniformBufferBaseType : byte
{
	UBMT_INVALID = 0,
	UBMT_BOOL = 1,
	UBMT_INT32 = 2,
	UBMT_UINT32 = 3,
	UBMT_FLOAT32 = 4,
	UBMT_TEXTURE = 5,
	UBMT_SRV = 6,
	UBMT_UAV = 7,
	UBMT_SAMPLER = 8,
	UBMT_RDG_TEXTURE = 9,
	UBMT_RDG_TEXTURE_ACCESS = 10,
	UBMT_RDG_TEXTURE_ACCESS_ARRAY = 11,
	UBMT_RDG_TEXTURE_SRV = 12,
	UBMT_RDG_TEXTURE_UAV = 13,
	UBMT_RDG_BUFFER_ACCESS = 14,
	UBMT_RDG_BUFFER_ACCESS_ARRAY = 15,
	UBMT_RDG_BUFFER_SRV = 16,
	UBMT_RDG_BUFFER_UAV = 17,
	UBMT_RDG_UNIFORM_BUFFER = 18,
	UBMT_NESTED_STRUCT = 19,
	UBMT_INCLUDED_STRUCT = 20,
	UBMT_REFERENCED_STRUCT = 21,
	UBMT_RENDER_TARGET_BINDING_SLOTS = 22,
	EUniformBufferBaseType_Num = 23,
	EUniformBufferBaseType_NumBits = 5
}
