namespace CUE4Parse.UE4.Versions;

public enum EUnrealEngineObjectUE5Version : uint
{
	INITIAL_VERSION = 1000u,
	NAMES_REFERENCED_FROM_EXPORT_DATA = 1001u,
	PAYLOAD_TOC = 1002u,
	OPTIONAL_RESOURCES = 1003u,
	LARGE_WORLD_COORDINATES = 1004u,
	REMOVE_OBJECT_EXPORT_PACKAGE_GUID = 1005u,
	TRACK_OBJECT_EXPORT_IS_INHERITED = 1006u,
	FSOFTOBJECTPATH_REMOVE_ASSET_PATH_FNAMES = 1007u,
	ADD_SOFTOBJECTPATH_LIST = 1008u,
	DATA_RESOURCES = 1009u,
	AUTOMATIC_VERSION_PLUS_ONE = 1010u,
	AUTOMATIC_VERSION = 1009u
}
